"""empty message

Revision ID: 8c037422dc4e
Revises: ea42d7078ba8
Create Date: 2021-04-24 12:55:43.974755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c037422dc4e'
down_revision = 'ea42d7078ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_markets', sa.Column('display_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_markets', 'display_name')
    # ### end Alembic commands ###
